# ESMPy Grid Cell Area Calculation

In [1]:
import numpy as np
import esmpy
esmpy.__version__

/home/ryan/.pyenv/versions/ESMPy-python3.10.5/lib/python3.10/site-packages/esmpy/interface/loadESMF.py:82: VersionWarning: ESMF installation version 8.4.0 beta snapshot, ESMPy version 8.4.0b13
  warnings.warn("ESMF installation version {}, ESMPy version {}".format(


'8.4.0b13'

## Make fake grid

In [2]:
lon = np.linspace(-114, 114, 20)
lon_b = np.linspace(-120, 120, 21)
lat = np.linspace(-57, 57, 20) # corners
lat_b = np.linspace(-60, 60, 21)
lon, lon_b, lat, lat_b

(array([-114., -102.,  -90.,  -78.,  -66.,  -54.,  -42.,  -30.,  -18.,
          -6.,    6.,   18.,   30.,   42.,   54.,   66.,   78.,   90.,
         102.,  114.]),
 array([-120., -108.,  -96.,  -84.,  -72.,  -60.,  -48.,  -36.,  -24.,
         -12.,    0.,   12.,   24.,   36.,   48.,   60.,   72.,   84.,
          96.,  108.,  120.]),
 array([-57., -51., -45., -39., -33., -27., -21., -15.,  -9.,  -3.,   3.,
          9.,  15.,  21.,  27.,  33.,  39.,  45.,  51.,  57.]),
 array([-60., -54., -48., -42., -36., -30., -24., -18., -12.,  -6.,   0.,
          6.,  12.,  18.,  24.,  30.,  36.,  42.,  48.,  54.,  60.]))

## Create Grid object

In [3]:
sourcegrid = esmpy.Grid(np.array([20,20]), 
                       staggerloc = esmpy.StaggerLoc.CENTER,
                       coord_sys = esmpy.CoordSys.SPH_DEG)

source_lon = sourcegrid.get_coords(0)
source_lat = sourcegrid.get_coords(1)
source_lon[...], source_lat[...] = np.meshgrid(lon, lat)

## Add corners


In [4]:
sourcegrid.add_coords(staggerloc = esmpy.StaggerLoc.CORNER_VCENTER)

source_lat_b = sourcegrid.get_coords(coord_dim = 1, 
                                     staggerloc = esmpy.StaggerLoc.CORNER)
source_lon_b = sourcegrid.get_coords(coord_dim = 0, 
                                     staggerloc = esmpy.StaggerLoc.CORNER)

source_lon_b[...], source_lat_b[...] = np.meshgrid(lon_b, lat_b)

## Retrieve areas

ESMF can only retrieve areas for the cells of a Grid via the Field class. The "add_user_area" parameter in the Grid constructor is used to specify customized grid cell areas for a Grid created from file only. Regardless, the Grid.area property is not yet hooked up to the values retrieved via Field.. that is confusing, sorry about that! 

In [5]:
sourcegridareafield = esmpy.Field(sourcegrid)
sourcegridareafield.get_area()
sourcegridareafield.data

array([[0.01189147, 0.01189147, 0.01189147, 0.01189147, 0.01189147,
        0.01189147, 0.01189147, 0.01189147, 0.01189147, 0.01189147,
        0.01189147, 0.01189147, 0.01189147, 0.01189147, 0.01189147,
        0.01189147, 0.01189147, 0.01189147, 0.01189147, 0.01189147],
       [0.01375531, 0.01375531, 0.01375531, 0.01375531, 0.01375531,
        0.01375531, 0.01375531, 0.01375531, 0.01375531, 0.01375531,
        0.01375531, 0.01375531, 0.01375531, 0.01375531, 0.01375531,
        0.01375531, 0.01375531, 0.01375531, 0.01375531, 0.01375531],
       [0.01547311, 0.01547311, 0.01547311, 0.01547311, 0.01547311,
        0.01547311, 0.01547311, 0.01547311, 0.01547311, 0.01547311,
        0.01547311, 0.01547311, 0.01547311, 0.01547311, 0.01547311,
        0.01547311, 0.01547311, 0.01547311, 0.01547311, 0.01547311],
       [0.0170251 , 0.0170251 , 0.0170251 , 0.0170251 , 0.0170251 ,
        0.0170251 , 0.0170251 , 0.0170251 , 0.0170251 , 0.0170251 ,
        0.0170251 , 0.0170251 , 0.0170251 , 0